name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build And Deploy
        id: builddeploy
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
          skip_deploy_on_missing_secrets: true
        env:
          SMARTSHEET_API_KEY: ${{ secrets.SMARTSHEET_API_KEY }}
      
      - name: Build Only (No Deploy)
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN == '' }}
        run: |
          echo "⚠️ Azure Static Web Apps API token not found!"
          echo "📋 To enable deployment:"
          echo "1. Create an Azure Static Web App resource"
          echo "2. Copy the deployment token from Azure Portal"
          echo "3. Add it as AZURE_STATIC_WEB_APPS_API_TOKEN in GitHub Secrets"
          echo "4. Also add SMARTSHEET_API_KEY in GitHub Secrets"
          echo "✅ Build completed successfully - ready for deployment!"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"